// Dahua products from the client-supplied Orient CCTV catalog pages.
// One entry per model; retailer prices and stock status are intentionally not imported.
export const products = [
  {
    "id": "dh-hac-hfw1500tlp-a",
    "brand": "Dahua",
    "model": "DH-HAC-HFW1500TLP-A",
    "title": "Dahua 5MP Bullet Camera",
    "category": "HDCVI Cameras",
    "text": "5MP bullet camera with infrared night vision and a built-in microphone.",
    "image": "/images/products/dahua/dh-hac-hfw1500tlp-a.jpg",
    "imageAlt": "Dahua 5MP Bullet Camera - DH-HAC-HFW1500TLP-A",
    "featured": true,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-hac-hfw1500tlp-a-5mp-bullet-cctv-camera-with-80m-night-vision-built-in-audio-outdoor-security-camera-pakistan/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2026/07/DH-HAC-HFW1500TLP-A-600x600.jpg"
  },
  {
    "id": "dh-hac-t1a21p-u-il-a",
    "brand": "Dahua",
    "model": "DH-HAC-T1A21P-U-IL-A",
    "title": "Dahua 2MP Dual Light Turret Camera",
    "category": "HDCVI Cameras",
    "text": "2MP turret camera with color imaging and a built-in microphone.",
    "image": "/images/products/dahua/dh-hac-t1a21p-u-il-a.jpg",
    "imageAlt": "Dahua 2MP Dual Light Turret Camera - DH-HAC-T1A21P-U-IL-A",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-hac-t1a21p-u-il-a-2mp-colormic-doom-camera/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/12/DAHUA-DH-HAC-T1A21P-U-IL-A-2MP-COLORMIC-DOOM-CAMERA.jpg"
  },
  {
    "id": "dh-hac-t1a51p-u-il-a",
    "brand": "Dahua",
    "model": "DH-HAC-T1A51P-U-IL-A",
    "title": "Dahua 5MP Dual Light Turret Camera",
    "category": "HDCVI Cameras",
    "text": "5MP turret camera with Smart Dual Light for day and night monitoring.",
    "image": "/images/products/dahua/dh-hac-t1a51p-u-il-a.jpg",
    "imageAlt": "Dahua 5MP Dual Light Turret Camera - DH-HAC-T1A51P-U-IL-A",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-hac-t1a51p-u-il-a-5mp-smart-dual-light-doom-camera/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/12/DAHUA-DH-HAC-T1A51P-U-IL-A-5MP-Smart-Dual-Light-Doom-Camera-1-600x600.jpg"
  },
  {
    "id": "dh-hac-t5e20p",
    "brand": "Dahua",
    "model": "DH-HAC-T5E20P",
    "title": "Dahua 2MP IR Turret Camera",
    "category": "HDCVI Cameras",
    "text": "2MP turret camera with infrared illumination for everyday CCTV coverage.",
    "image": "/images/products/dahua/dh-hac-t5e20p.jpg",
    "imageAlt": "Dahua 2MP IR Turret Camera - DH-HAC-T5E20P",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-hac-t5e20p-2mp-dome-camera/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/12/DAHUA-DH-HAC-T5E20P-2MP-DOME-CAMERA-1-600x600.jpg"
  },
  {
    "id": "dh-ipc-b1e29-a-il",
    "brand": "Dahua",
    "model": "DH-IPC-B1E29-A-IL",
    "title": "Dahua 2MP IP Bullet Camera",
    "category": "IP Cameras",
    "text": "2MP network bullet camera with Smart Dual Light for outdoor monitoring.",
    "image": "/images/products/dahua/dh-ipc-b1e29-a-il.jpg",
    "imageAlt": "Dahua 2MP IP Bullet Camera - DH-IPC-B1E29-A-IL",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-ipc-b1e29-a-il-2mp-full-color-bullet-camera-pakistan/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/05/16-600x600.jpg"
  },
  {
    "id": "dh-ipc-hdw1839tp-a-il",
    "brand": "Dahua",
    "model": "DH-IPC-HDW1839TP-A-IL",
    "title": "Dahua 8MP Dual Light Eyeball Camera",
    "category": "IP Cameras",
    "text": "8MP network camera with Smart Dual Light and built-in audio.",
    "image": "/images/products/dahua/dh-ipc-hdw1839tp-a-il.png",
    "imageAlt": "Dahua 8MP Dual Light Eyeball Camera - DH-IPC-HDW1839TP-A-IL",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-ipc-hdw1839tp-a-il-8mp-smart-dual-color-ip-camera-with-audio-night-vision/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2026/05/1-13-600x600.png"
  },
  {
    "id": "dh-ipc-hdw2431tp-as-s2",
    "brand": "Dahua",
    "model": "DH-IPC-HDW2431TP-AS-S2",
    "title": "Dahua 4MP IP Eyeball Camera",
    "category": "IP Cameras",
    "text": "4MP network camera with a built-in microphone for video and audio coverage.",
    "image": "/images/products/dahua/dh-ipc-hdw2431tp-as-s2.jpg",
    "imageAlt": "Dahua 4MP IP Eyeball Camera - DH-IPC-HDW2431TP-AS-S2",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-ipc-hdw2431tp-as-s2-4mp-network-dome-ip-camera-built-in-mic-full-hd-cctv-camera/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2026/07/DH-IPC-HDW2431TP-AS-S2-600x600.jpg"
  },
  {
    "id": "dh-ipc-hdw2531tp-as-s2",
    "brand": "Dahua",
    "model": "DH-IPC-HDW2531TP-AS-S2",
    "title": "Dahua 5MP IP Eyeball Camera",
    "category": "IP Cameras",
    "text": "5MP network camera with a built-in microphone and infrared night vision.",
    "image": "/images/products/dahua/dh-ipc-hdw2531tp-as-s2.jpg",
    "imageAlt": "Dahua 5MP IP Eyeball Camera - DH-IPC-HDW2531TP-AS-S2",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-ipc-hdw2531tp-as-s2-5mp-ip-dome-security-camera-with-built-in-microphone-smart-ir-night-vision/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2026/07/5mp-600x600.jpg"
  },
  {
    "id": "dh-ipc-hfw1239tl1-pv-s6",
    "brand": "Dahua",
    "model": "DH-IPC-HFW1239TL1-PV-S6",
    "title": "Dahua 2MP Two-Way Talk Bullet Camera",
    "category": "IP Cameras",
    "text": "2MP network bullet camera with dual lighting and two-way talk.",
    "image": "/images/products/dahua/dh-ipc-hfw1239tl1-pv-s6.jpg",
    "imageAlt": "Dahua 2MP Two-Way Talk Bullet Camera - DH-IPC-HFW1239TL1-PV-S6",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-ipc-hfw1239tl1-pv-s6-2mp-dual-light-two-way-talk-ip-bullet-camera-full-hd-security-system-pakistan/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/08/Dahua-Camera-600x600.jpg"
  },
  {
    "id": "dh-ipc-hfw2441s-s",
    "brand": "Dahua",
    "model": "DH-IPC-HFW2441S-S",
    "title": "Dahua 4MP WizSense Bullet Camera",
    "category": "IP Cameras",
    "text": "4MP WizSense network camera with PoE connectivity and a built-in microphone.",
    "image": "/images/products/dahua/dh-ipc-hfw2441s-s.jpg",
    "imageAlt": "Dahua 4MP WizSense Bullet Camera - DH-IPC-HFW2441S-S",
    "featured": true,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-ipc-hfw2441s-s-4mp-plus-bullet-wizsense-network-ip-built-in-mic-poe-ir30m-ip67-smd/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/07/17-600x600.jpg"
  },
  {
    "id": "dh-ipc-hfw2849s-s-il",
    "brand": "Dahua",
    "model": "DH-IPC-HFW2849S-S-IL",
    "title": "Dahua 8MP WizSense Bullet Camera",
    "category": "IP Cameras",
    "text": "8MP WizSense camera with Smart Dual Light and built-in audio.",
    "image": "/images/products/dahua/dh-ipc-hfw2849s-s-il.jpg",
    "imageAlt": "Dahua 8MP WizSense Bullet Camera - DH-IPC-HFW2849S-S-IL",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-ipc-hfw2849s-s-il-8mp-2-8mm-poe-built-in-mic-ip67-smd-24-hours-full-color-ir-30m-smart-dual-light-wizsense-camera/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/02/18-1-600x600.jpg"
  },
  {
    "id": "dh-ipc-hfw3441t-zas",
    "brand": "Dahua",
    "model": "DH-IPC-HFW3441T-ZAS",
    "title": "Dahua 4MP Varifocal Bullet Camera",
    "category": "IP Cameras",
    "text": "4MP network bullet camera with a varifocal lens and infrared illumination.",
    "image": "/images/products/dahua/dh-ipc-hfw3441t-zas.jpg",
    "imageAlt": "Dahua 4MP Varifocal Bullet Camera - DH-IPC-HFW3441T-ZAS",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-ipc-hfw3441t-zas/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/12/DAHUA-DH-IPC-HFW3441T-ZAS-4MP-Lite-AI-IR-Vari-focal-Bullet-Network-Camera-600x600.jpg"
  },
  {
    "id": "dh-ipc-t1e29-a-il",
    "brand": "Dahua",
    "model": "DH-IPC-T1E29-A-IL",
    "title": "Dahua 2MP IP Turret Camera",
    "category": "IP Cameras",
    "text": "2MP network turret camera with Smart Dual Light for day and night coverage.",
    "image": "/images/products/dahua/dh-ipc-t1e29-a-il.jpg",
    "imageAlt": "Dahua 2MP IP Turret Camera - DH-IPC-T1E29-A-IL",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-ipc-t1e29-a-il-2mp-full-color-dome-camera-pakistan/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/05/19-600x600.jpg"
  },
  {
    "id": "dh-ipc-t1e49-a-il",
    "brand": "Dahua",
    "model": "DH-IPC-T1E49-A-IL",
    "title": "Dahua 4MP IP Turret Camera",
    "category": "IP Cameras",
    "text": "4MP Eco Series network camera with a built-in microphone and dual lighting.",
    "image": "/images/products/dahua/dh-ipc-t1e49-a-il.jpg",
    "imageAlt": "Dahua 4MP IP Turret Camera - DH-IPC-T1E49-A-IL",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-ipc-t1e49-a-il-4mp-dome-ip-camera-with-built-in-mic-full-color-night-vision-eco-series/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/07/20-600x600.jpg"
  },
  {
    "id": "dh-sd2c400na-b-pv-pro",
    "brand": "Dahua",
    "model": "DH-SD2C400NA-B-PV-PRO",
    "title": "Dahua 4MP Mini PT WizColor Camera",
    "category": "PT Cameras",
    "text": "Compact 4MP WizColor network camera with pan-and-tilt monitoring.",
    "image": "/images/products/dahua/dh-sd2c400na-b-pv-pro.jpg",
    "imageAlt": "Dahua 4MP Mini PT WizColor Camera - DH-SD2C400NA-B-PV-PRO",
    "featured": true,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-sd2c400na-b-pv-pro-mini-pt-wizcolor-4mp-ip-camera/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/12/Dahua-DH-SD2C400NA-B-PV-PRO-Mini-PT-WizColor-4MP-IP-CAMERA-600x600.jpg"
  },
  {
    "id": "dh-pfs4226-24et-240",
    "brand": "Dahua",
    "model": "DH-PFS4226-24ET-240",
    "title": "Dahua 24-Port PoE Switch",
    "category": "Network & Cabling",
    "text": "Managed PoE switch with 24 PoE ports for connecting IP camera systems.",
    "image": "/images/products/dahua/dh-pfs4226-24et-240.jpg",
    "imageAlt": "Dahua 24-Port PoE Switch - DH-PFS4226-24ET-240",
    "featured": true,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-pfs4226-24et-240-dahua-24-port-poe-switch/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/12/DAHUA-DH-PFS4226-24ET-240-Dahua-24-Port-POE-Switch-1-600x600.jpg"
  },
  {
    "id": "dh-pfm920i-6u-c",
    "brand": "Dahua",
    "model": "DH-PFM920I-6U-C",
    "title": "Dahua CAT6 Copper Cable",
    "category": "Network & Cabling",
    "text": "305-metre CAT6 copper cable roll for structured network and CCTV installations.",
    "image": "/images/products/dahua/dh-pfm920i-6u-c.jpg",
    "imageAlt": "Dahua CAT6 Copper Cable - DH-PFM920I-6U-C",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dh-pfm920i-6u-c-cat6-23awg-copper-305-meter-cable-roll/",
    "imageSourceUrl": "https://cdn-ilcelnn.nitrocdn.com/RqHjnrwsixciMzdjciQEyMHItMVJYxLT/assets/images/optimized/rev-0368711/orientcctv.com/wp-content/uploads/2025/12/DAHUA-DH-PFM920I-6U-C-CAT6-23AWG-COPPER-305-METER-CABLE-ROLL-1-600x600.jpg"
  },
  {
    "id": "dhi-kta02",
    "brand": "Dahua",
    "model": "DHI-KTA02",
    "title": "Dahua 7-Inch Video Intercom Kit",
    "category": "Accessories",
    "text": "White analog video intercom kit with a 7-inch indoor display.",
    "image": "/images/products/dahua/dhi-kta02.webp",
    "imageAlt": "Dahua 7-Inch Video Intercom Kit - DHI-KTA02",
    "featured": true,
    "sourceUrl": "https://orientcctv.com/product/dahua-dhi-kta02-intercom-white/",
    "imageSourceUrl": "https://orientcctv.com/wp-content/uploads/2025/09/KTA-02-600x600.webp"
  },
  {
    "id": "dahua-microsd-memory-card",
    "brand": "Dahua",
    "model": "32 / 64 / 128 / 256 GB",
    "title": "Dahua MicroSD Memory Card",
    "category": "Accessories",
    "text": "MicroSD storage options for compatible cameras and other Dahua devices.",
    "image": "/images/products/dahua/dahua-microsd-memory-card.webp",
    "imageAlt": "Dahua MicroSD Memory Card - 32 / 64 / 128 / 256 GB",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-original-32-64-128-microsd-memory-card-95-mb-s-tf-high-speed-card-for-ip-wifi-camera-vto-vth-various-digital-products/",
    "imageSourceUrl": "https://orientcctv.com/wp-content/uploads/2025/09/kf-Sa22d74c36d1d486eb889927f11bc444fL-600x600.webp"
  },
  {
    "id": "dhi-isc-d106",
    "brand": "Dahua",
    "model": "DHI-ISC-D106",
    "title": "Dahua 6-Zone Walk-Through Detector",
    "category": "Accessories",
    "text": "Walk-through metal detector with six detection zones for entrance screening.",
    "image": "/images/products/dahua/dhi-isc-d106.jpg",
    "imageAlt": "Dahua 6-Zone Walk-Through Detector - DHI-ISC-D106",
    "featured": false,
    "sourceUrl": "https://orientcctv.com/product/dahua-dhi-isc-d106-walk-through-gate-6-zone/",
    "imageSourceUrl": "https://orientcctv.com/wp-content/uploads/2025/12/DAHUA-DHI-ISC-D106-WALK-THROUGH-GATE-6-Zone-1-600x600.jpg"
  }
];

export const productCategories = [...new Set(products.map((product) => product.category))];

